import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt available in multiple colors.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Clothing",
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with this advanced smartwatch featuring heart rate monitoring.",
    price: 299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    inStock: true,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "4",
    name: "Artisan Coffee Beans",
    description: "Premium single-origin coffee beans roasted to perfection for the ultimate coffee experience.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Food & Beverage",
    inStock: true,
    rating: 4.9,
    reviews: 203,
  },
  {
    id: "5",
    name: "Minimalist Desk Lamp",
    description: "Modern LED desk lamp with adjustable brightness and sleek minimalist design.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home & Office",
    inStock: false,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "6",
    name: "Yoga Mat Pro",
    description: "Professional-grade yoga mat with superior grip and cushioning for all yoga practices.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports & Fitness",
    inStock: true,
    rating: 4.8,
    reviews: 91,
  },
]
